"""add_sso_provider_subject_unique_constraint_to_user

Revision ID: 0004
Revises: 0003
Create Date: 2024-08-27 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sso_provider_subject', 'users', ['sso_provider', 'sso_subject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sso_provider_subject', 'users', type_='unique')
    # ### end Alembic commands ###
